heat_template_version: 2013-05-23
description: Template za instalaciju Hadoop i Hive distribucije.

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach server to.

resources:
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
    handle: { get_resource: wait_handle }
    count: 1
    timeout: 600

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
    name: db_server_security_group
    rules:
    - port_range_min: 3306
    port_range_max: 3306
    protocol: tcp
    direction: ingress
    - port_range_min: 3306
    port_range_max: 3306
    protocol: tcp
    direction: egress

  port:
    type: OS::Neutron::Port
    properties:
    network: { get_param: private_network }
    security_groups:
    - { get_resource: security_group }
    - default
  
  hadoop_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
    networks:
      - port: { get_resource: port }
    user_data_format: RAW
    user_data:
      str_replace:
        params:
          wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
        template: |
          #!/bin/bash

          #korištenje ako već imamo podešenu sliku

          su - hadoop
          cd /home/hadoop/
          source .bashrc

          #pokretanj hadoopa
          cd hadoop/sbin
          ./start-all.sh

          #pokretanje hive servera
          cd /home/hadoop/hive/bin
          ./hiveserver2

outputs:
  ip:
    description: The IP address of the hadoop instance.
    value: { get_attr: [hadoop_instance, first_address] }
